'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class City
    Public Sub New()
        Me.Countries = New HashSet(Of Country)()
        Me.Customers = New HashSet(Of Customer)()
    End Sub

    Public Property CityId() As Integer
    Public Property CityName() As String
    Public Property CountryId() As Integer?

    Public Overridable Property Country() As Country
    Public Overridable Property Countries() As ICollection(Of Country)
    Public Overridable Property Customers() As ICollection(Of Customer)
End Class

Partial Public Class Country
    Public Sub New()
        Me.Cities = New HashSet(Of City)()
        Me.Customers = New HashSet(Of Customer)()
    End Sub

    Public Property CountryId() As Integer
    Public Property CountryName() As String
    Public Property CapitalId() As Integer?

    Public Overridable Property Cities() As ICollection(Of City)
    Public Overridable Property City() As City
    Public Overridable Property Customers() As ICollection(Of Customer)
End Class

Partial Public Class Customer
    Public Property CustomerId() As Integer
    Public Property CustomerName() As String
    Public Property CountryId() As Integer?
    Public Property CityId() As Integer?

    Public Overridable Property City() As City
    Public Overridable Property Country() As Country
End Class
