//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class City
{
    public City()
    {
        this.Countries = new HashSet<Country>();
        this.Customers = new HashSet<Customer>();
    }

    public int CityId { get; set; }
    public string CityName { get; set; }
    public Nullable<int> CountryId { get; set; }

    public virtual Country Country { get; set; }
    public virtual ICollection<Country> Countries { get; set; }
    public virtual ICollection<Customer> Customers { get; set; }
}

public partial class Country
{
    public Country()
    {
        this.Cities = new HashSet<City>();
        this.Customers = new HashSet<Customer>();
    }

    public int CountryId { get; set; }
    public string CountryName { get; set; }
    public Nullable<int> CapitalId { get; set; }

    public virtual ICollection<City> Cities { get; set; }
    public virtual City City { get; set; }
    public virtual ICollection<Customer> Customers { get; set; }
}

public partial class Customer
{
    public int CustomerId { get; set; }
    public string CustomerName { get; set; }
    public Nullable<int> CountryId { get; set; }
    public Nullable<int> CityId { get; set; }

    public virtual City City { get; set; }
    public virtual Country Country { get; set; }
}
